db:
  username: ${username.value:postgres}
  password: root
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa


logging:
  level:
    root: INFO
    com.dmdev.spring.database.pool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: dmdev.log
    path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1057732900495-41ud7ntlosdmgtkconf59oe0a4vmlcnd.apps.googleusercontent.com
            client-secret: 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
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile
  messages:
    basename: messages

springdoc:
  swagger-ui:
    oauth:
      client-id: 1057732900495-41ud7ntlosdmgtkconf59oe0a4vmlcnd.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
app:
  common:
    logging:
      enabled: true
      level: INFO